dist: trusty
sudo: false

language: go

go_import_path: github.com/src-d/datasets
go:
  - 1.9.x
  - 1.10.x

before_install:
  - go get -v github.com/golang/lint/golint

script:
  - if [[ "$(go version)" != *go1.8* ]]; then go vet ./...; fi
  - lintwarns=$(golint ./... | grep src-d/datasets || true)
  - if [ ! -z $lintwarns ]; then echo $lintwarns; false; fi
  - make test-coverage

after_success:
  - make codecov

jobs:
  include:
    - stage: deploy
      if: tag IS present
      os: linux
      go: 1.10.x
      script: make packages
      deploy:
        provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file_glob: true
        file: build/*.tar.gz
        skip_cleanup: true

notifications:
  email: false
